language: php

php:
  - 7.1

before_script:
  - composer update
  - if [ "$DEPENDENCIES" = 'low' ] ; then composer update --prefer-source --prefer-lowest --prefer-stable; fi
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi
  - git clone https://github.com/padraic/humbug.git && cd humbug && composer install && cd ..
  - chmod +x ./build/check-humbug-mutators.php
  - pwd

script:
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --coverage-text --coverage-clover ./clover.xml --colors
  - ./vendor/bin/phpcs
  - ./humbug/bin/humbug
  - ./build/check-humbug-mutators.php

env:
  matrix:
    - DEPENDENCIES="high"
    - DEPENDENCIES="low"

matrix:
  allow_failures:
    - php: hhvm

after_script:
  - pwd
  - ls -Al
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml
