language: php

php:
  - 7.3
  - 8.0

env:
  matrix:
    - DEPENDENCIES="high"
    - DEPENDENCIES="--prefer-lowest --prefer-stable"

before_script:
  - composer update --prefer-dist $DEPENDENCIES
  - git clone https://github.com/padraic/humbug.git && cd humbug && composer install && cd ..
  - chmod +x ./build/check-humbug-mutators.php

script:
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --coverage-clover ../clover.xml
  - ./vendor/bin/phpcs
  - ./humbug/bin/humbug
  - ./build/check-humbug-mutators.php

after_script:
  - if [ $TRAVIS_PHP_VERSION = '7.3' ]; then wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi
